### ISSUE TITLE
This repo is the resulting template for the CLAA?

### ISSUE THREAD

**Issue by aadamsx** [thepassle/create-lit-app-advanced#2]
Is this repo is the resulting template for the Create Lit App Advanced?  

This is NOT the actual node app that gets installed when you run this command correct?

```
npm install --global create-lit-app-advanced
```

**Comment by thepassle** [comment]
Correct, this is the template that gets installed when you use `create-lit-app-advanced`, you can find the node app at: https://github.com/thepassle/create-lit-app-cli-advanced
