### ISSUE TITLE
Authenication

### ISSUE THREAD

**Issue by aadamsx** [thepassle/create-lit-app-advanced#4]
I understand you do not think Authentication should be added by default, but could the OPTION to add Authentication, via something like @sheideman's [solution](https://github.com/thepassle/create-lit-app/issues/3#issuecomment-419671436)

or just Passpor.js be added instead?  Something like:

```
create-lit-app-advanced my-app --auth
```

If not, [examples](https://github.com/thepassle/create-lit-app/issues/3#issuecomment-421493070) on how to build this is would be amazing!  Thank you!

**Comment by thepassle** [comment]
https://github.com/thepassle/create-lit-app-advanced/issues/3

**Comment by aadamsx** [comment]
> Arguably its already too verbose with redux/express api, and they should be documented in the docs instead. 

Do you mean it's too much code to write?  It's something every app needs.

> Create-lit-app was made to help people get started with lit-html/lit-element/webcomponents, you can find any tutorial on passportjs authentication and add any frontend to it.

After giving this more thought, I think Authentication and the front end wired up to it is one of the biggest obstacles to getting started with any app.  

I think you could make it optional or even have a flag to remove the code for it if one wishes.  

I don't think docs are enough... if not adding it to this template, what about an example with auth built in?

**Comment by sheideman** [comment]
Here is the link to my repo that uses JWT [create-lit-app auth with JWT](https://github.com/sheideman/Create-Lit-App-Auth-Starter)

**Comment by thepassle** [comment]
Exactly what I meant with:

>Additionally, create-lit-app is open source, and I encourage people to contribute, or simply fork and provide a functionality that you feel is missing.

Really awesome work! I'll add a link to this repo in the README of create-lit-app.

**Comment by sheideman** [comment]
Thanks @thepassle ! I am working on a graphql implementation as well. I will post that as well when it is done. 👍

**Comment by thepassle** [comment]
Awesome, keep me posted! Would it be possible to upload a live demo of it, as well as a screenshot in the README of create-lit-app-auth-starter?

**Comment by thepassle** [comment]
Great idea, i'll have some time to work on it tomorrow. Lets keep eachother updated and again, feel free to reach out if you need a hand.

**Comment by sheideman** [comment]
Hey man, sorry it took so long, I had some unanticipated time sucks the
last few days... App is pushed and readme is updated with screenshots. Let
me know if you want to see anything else! I found an interesting apollo
client provider project here: https://github.com/bennypowers/lit-apollo  I
am going to use that for the graphql implementation example. Just a heads
up that more is on the way! 😉

**Comment by thepassle** [comment]
Looking great! Thanks for taking the time to upload a working demo as well, adds a lot of value imo.

If theres some feedback I could give you, make sure you're up to date with the latest version of CLA and LitElement, i noticed the auth starter is still on litelement 0.5.x, and theres been breaking changes in the API (that i think might clash with Benny's latest LitApollo version). I can probably help update and make a PR, but it wont be until sometime next week.

Thanks again for your efforts!

**Comment by sheideman** [comment]
Thanks for the heads up! I have been working in Salesforce for the last
month so I haven't had a time to catch up. Let me see what I can tackle and
we can regroup next week. 👍

**Comment by sheideman** [comment]
I had some time this afternoon so I upgraded the repo to work with the 0.6.x LitElement changes [https://github.com/sheideman/Create-Lit-App-Auth-Starter](url) I also fixed some annoying little mistakes while I was at it.
